### ISSUE TITLE
Incorrect type of deletion

### ISSUE THREAD

**Issue by TheDarkFlame** [Error998/SAMUpdater#6]
Application sends items to recycle bin instead of deleting permanently, this affects my OCD in the most amazingly scary way every time i run the updater

**Comment by Error998** [comment]
Its a feature not a bug. As I do not fully trust what SkyNet does with ur
files Im instructing it to place removed files in the recycle bin.

**Comment by TheDarkFlame** [comment]
OCD still is killing me though :/

**Comment by Error998** [comment]
Left the recycle bin option for debugging purposes or for those that are paranoid :smiling_imp: 

Edit %appdata%\SAMUpdater\Settings\settings.ini if you would like the updater to delete files to Recycle bin instead of the default behavior of permanently deleting files.
